### ISSUE TITLE
after and before content feature maybe

### ISSUE THREAD

**Issue by DasdWaller** [croutonn/tailwindcss-pseudo-elements#46]
Why cant this plugin do something like this.

```html
<p class="text-lg text-blue-600" tw-before="❤️️" tw-after="❤️️">Tailwind CSS</p>
```

by default (or not) `before` and `after` include.
```css
*:before {
  content: attr(tw-before)
}

*:after {
  content: attr(tw-after)
}
```

The user will have the option to turn off/on on options.
```
plugins: [
  require('tailwindcss-pseudo-elements')({
    defaultContent: false
  })
],
```

Optional: if user create a utilities class with content plugin is better to overwrite or pass `content: attr(tw-*)`
